### ISSUE TITLE
TimeTracker uninitialized constant SortHelper::SortCriteria

### ISSUE THREAD

**Issue by magefan** [hicknhack-software/redmine_time_tracker#219]
Hello and thank you for your plugin.  We have faced with the issue when we try to open TimeTracker link, we get this error

```
Started GET "/tt_menu_switcher/index" for 172.68.246.191 at 2017-11-27 21:32:49 +0100
Processing by TtMenuSwitcherController#index as HTML
  Current user: ihor (id=1)
Redirected to http://pm.magefan.com/tt_overview
Completed 302 Found in 15ms (ActiveRecord: 8.1ms)
Started GET "/tt_overview" for 172.68.246.191 at 2017-11-27 21:32:49 +0100
Processing by TtOverviewController#index as HTML
  Current user: ihor (id=1)
Completed 500 Internal Server Error in 25ms (ActiveRecord: 3.7ms)

NameError (uninitialized constant SortHelper::SortCriteria):
  plugins/redmine_time_tracker/app/helpers/tt_sort_helper.rb:6:in `tt_sort_update'
  plugins/redmine_time_tracker/app/controllers/tt_overview_controller.rb:29:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```

Redmine information
```

Environment:
  Redmine version                3.4.2.stable
  Ruby version                   2.3.1-p112 (2016-04-26) [x86_64-linux-gnu]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.3
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.4.5
  redmine_image_clipboard_paste  3.3.0
  redmine_issue_checklist        2.1.0
  redmine_issue_todo_lists       1.1.2
  redmine_people                 1.3.2
  redmine_slack                  0.2
  redmine_time_tracker           0.10.6

  vault                          0.3.3
```
Do you have any solution for it?

**Comment by jume-dev** [comment]
Hi,
this repository is no longer maintained and i honestly have no idea what the problem could be. Please try our new plugin https://github.com/hicknhack-software/redmine_hourglass (there is an migration option to convert data from this old plugin to the new one).
